server:
  port: 8083

swagger:
  title: dousl-starter-swagger
  description: learn swagger 2.x
  version: 1.9.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: dousl
    url: http://blog.douslspace.com
    email: 384602183@qq.com
  base-package: com.dousl.learnboot1
  base-path: /**
  ui-config:
    tags-sorter: alpha
    operations-sorter: alpha