#服务器相关
server:
  port: 8081

#数据库相关
spring:
  datasource:
    url: jdbc:mysql://123.57.75.66:3306/dousl_learn
    username: root
    password: dousl01MySQL!Remote
    driver-class-name: com.mysql.jdbc.Driver